# Generated by Django 5.1 on 2024-09-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
