# Generated by Django 5.1 on 2024-09-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_shippingaddress_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
