# Generated by Django 5.1 on 2024-09-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
        ('Orders', '0007_remove_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='order_items', to='Cart.cart'),
        ),
    ]
