# Generated by Django 5.1 on 2024-09-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
